### ISSUE TITLE
[Bug]: Svelte LineChart runs in dev but not production

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1381]
### Contact Details

nstuyvesant@gmail.com

### What happened?

I created a Svelte component in SvelteKit with a LineChart that runs fine in dev. Once you build it and run it in production, it throws a JavaScript error (shown below).

1. `git clone https://github.com/nstuyvesant/carbon-example.git`
2. `cd carbon-example`
3. `npm install`
4. `npm run build`
5. `node build`
6. JavaScript error appears (shown below).

### Version

@carbon/charts-svelte@1.0.4

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.53 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    @carbon/charts-svelte: ^1.0.4 => 1.0.4 
    @sveltejs/adapter-node: next => 1.0.0-next.76 
    @sveltejs/kit: next => 1.0.0-next.345 
    svelte: ^3.48.0 => 3.48.0 

### Data & options used

```js
If you `npm run dev`, no error occurs.
```

### Relevant log output

```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '2')
    at u (index.svelte-64343f7e.js:1:109197)
    at s (index.svelte-64343f7e.js:1:108955)
    at c.ticks (index.svelte-64343f7e.js:1:118840)
    at n.render (index.svelte-64343f7e.js:73:13561)
    at index.svelte-64343f7e.js:73:25017
    at Array.forEach (<anonymous>)
    at n.render (index.svelte-64343f7e.js:73:24975)
    at index.svelte-64343f7e.js:73:10535
    at Array.forEach (<anonymous>)
    at HTMLDivElement.<anonymous> (index.svelte-64343f7e.js:73:10465)
u @ index.svelte-64343f7e.js:1
s @ index.svelte-64343f7e.js:1
c.ticks @ index.svelte-64343f7e.js:1
n.render @ index.svelte-64343f7e.js:73
(anonymous) @ index.svelte-64343f7e.js:73
n.render @ index.svelte-64343f7e.js:73
(anonymous) @ index.svelte-64343f7e.js:73
(anonymous) @ index.svelte-64343f7e.js:73
Gb @ index.svelte-64343f7e.js:1
n.render @ index.svelte-64343f7e.js:73
(anonymous) @ index.svelte-64343f7e.js:73
(anonymous) @ index.svelte-64343f7e.js:73
Gb @ index.svelte-64343f7e.js:1
n.render @ index.svelte-64343f7e.js:73
(anonymous) @ index.svelte-64343f7e.js:84
t.update @ index.svelte-64343f7e.js:84
t.init @ index.svelte-64343f7e.js:84
n @ index.svelte-64343f7e.js:84
(anonymous) @ index.svelte-64343f7e.js:84
P @ index-1f8e7bcf.js:1
(anonymous) @ index-1f8e7bcf.js:1
z @ index-1f8e7bcf.js:1
Dt @ index-1f8e7bcf.js:1
Ut @ start-cb6a2ace.js:1
Ce @ start-cb6a2ace.js:1
ge @ start-cb6a2ace.js:1
```
```


### Codesandbox example

https://github.com/nstuyvesant/carbon-example

**Comment by nstuyvesant** [comment]
Resolved in @carbon/charts-svelte@1.1.0
